<?php
// Developed by Dennis Stevense for Digital Deployment

define('FACEBOOK_CONNECT_APP_ID', 'facebook_connect_app_id');
define('FACEBOOK_CONNECT_SITE_LIKE_PATH', 'facebook_connect_site_like_path');
define('FACEBOOK_CONNECT_NODE_LIKE_BUTTONS', 'facebook_connect_node_like_buttons');

function facebook_connect_menu() {
  $items = array();
  
  $items['admin/settings/facebook_connect'] = array(
    'title' => 'Facebook connect',
    'description' => 'Configure Facebook integration with your site.',
    'page callback'  => 'drupal_get_form',
    'page arguments' => array('facebook_connect_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'facebook_connect.admin.inc',
  );
  
  return $items;
}

function facebook_connect_block($op = 'list', $delta = 0, $form_values = array()) {
  switch ($op) {
    case 'list':
      $blocks = array();
      
      $blocks['login_box'] = array(
        'info' => t('Facebook connect login box'),
        'cache' => BLOCK_CACHE_GLOBAL,
      );
      
      $blocks['like_button_site'] = array(
        'info' => t('Facebook connect site like button'),
        'cache' => BLOCK_CACHE_GLOBAL,
      );
      
      return $blocks;
      
    case 'view':
      $function = 'facebook_connect_block_' . $delta . '_view';
    
      if (function_exists($function)) {
        return call_user_func($function);
      }
      else {
        return;
      }
  }
}

function facebook_connect_block_login_box_view() {
  return array(
    'content' => facebook_connect_login_box(),
  );
}

function facebook_connect_block_like_button_site_view() {
  return array(
    'content' => facebook_connect_like_button_site(),
  );
}

function facebook_connect_link($type, $object, $teaser = FALSE) {
  $links = array();
  
  if ($type == 'node' && $teaser && variable_get(FACEBOOK_CONNECT_NODE_LIKE_BUTTONS, FALSE)) {
    $node = $object;
    
    $links['facebook_connect_like_button'] = array(
      'title' => facebook_connect_like_button('node/' . $node->nid),
      'html' => TRUE,
    );
  }
  
  return $links;
}

function facebook_connect_theme() {
  $theme = array();
  
  $theme['facebook_connect_login_box'] = array(
    'template' => 'facebook-connect-login-box',
  );
  
  $theme['facebook_connect_like_button'] = array(
    'arguments' => array('like_path' => NULL),
    'template' => 'facebook-connect-like-button',
  );
  
  return $theme;
}

function facebook_connect_login_box() {
  drupal_add_css(drupal_get_path('module', 'facebook_connect') . '/facebook_connect.css');
  drupal_add_js(drupal_get_path('module', 'facebook_connect') . '/facebook_connect.js');
  
  $settings = array(
    'appID' => variable_get(FACEBOOK_CONNECT_APP_ID, NULL),
  );
  drupal_add_js(array('facebookConnect' => $settings), 'setting');

  return theme('facebook_connect_login_box');
}

function facebook_connect_like_button($like_path = NULL) {
  drupal_add_css(drupal_get_path('module', 'facebook_connect') . '/facebook_connect.css');
  drupal_add_js(drupal_get_path('module', 'facebook_connect') . '/facebook_connect.js');
  
  return theme('facebook_connect_like_button', $like_path);
}

function facebook_connect_like_button_site() {
  $like_path = variable_get(FACEBOOK_CONNECT_SITE_LIKE_PATH, NULL);
  
  if (empty($like_path)) {
    $like_path = '<front>';
  }
  
  return facebook_connect_like_button($like_path);
}

function template_preprocess_facebook_connect_like_button(&$variables) {
  if (!empty($variables['like_path'])) {
    $variables['like_url'] = url($variables['like_path'], array('absolute' => TRUE));
  }
  else {
    $variables['like_url'] = NULL;
  }
  
}
